version: '3'

services:
  db:
    image: mysql:5.6
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=zergling
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
  app:
    build: .
    ports:
      - "1337:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
