version: '3'

services:
  db:
    image: mysql:5.6
    expose:
      - 3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
  app:
    build: .
    ports:
      - "1337:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
